name: GeoLocation CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: docker-compose run --rm -e "MIX_ENV=test"  -e "PGDATABASE=geo_location_test" app mix do deps.get, compile --warnings-as-errors, test

